### ISSUE TITLE
new Error in build 102-105

### ISSUE THREAD

**Issue by tuanjr** [James137137/FactionChat#28]
http://paste.ubuntu.com/17447173/

**Comment by James137137** [comment]
try http://jenkins.lolnet.co.nz/job/FactionChat/104/

**Comment by James137137** [comment]
also could you post the message you sent? was it with the $ symbol?

**Comment by James137137** [comment]
@tuanjr is it fixed now?

**Comment by tuanjr** [comment]
now i use factions chat build 105, this error still not fixed

**Comment by James137137** [comment]
what messages are you typing?

**Comment by tuanjr** [comment]
message contain "$" symbol

**Comment by James137137** [comment]
ok. could you pastebin your config.yml and the console error here?

**Comment by tuanjr** [comment]
error: http://paste.ubuntu.com/18653863/
config: http://paste.ubuntu.com/18653915/

**Comment by James137137** [comment]
ok could you delete/backup your config.yml and let it regen. else maybe the build in jenkins isn't the latest....

**Comment by James137137** [comment]
i'll double check soon

**Comment by James137137** [comment]
yeah. it looks like it failed to build

**Comment by James137137** [comment]
could you test http://dev.bukkit.org/bukkit-plugins/factionchat/files/124-faction-chat-v1-10-0-pre-2/ for me?

**Comment by James137137** [comment]
yeah its something to do with gravitylow repo's that is causing the jenkins to not build. should be fixed very soon

**Comment by James137137** [comment]
see http://jenkins.lolnet.co.nz/job/FactionChat/111/

**Comment by tuanjr** [comment]
just try build 101, confirm error is fixed

**Comment by tuanjr** [comment]
@James137137 
Sorry, but i'm just found new error http://paste.ubuntu.com/18791787/
and, this message cause by Factions chat?:
`[Server thread/INFO]: This command is not supported in console yet!`

**Comment by James137137** [comment]
yeah... looks like it's mine

**Comment by James137137** [comment]
seems to be the same error....

format = format.replaceAll("MESSAGE", message);


I feel like making my own replaceAll method....

**Comment by James137137** [comment]
ok I think I fixed it.

I shouldn't use replaceAll just replace from string..... pushing and building now

**Comment by tuanjr** [comment]
Thank! :dancers:

**Comment by James137137** [comment]
building now

**Comment by James137137** [comment]
http://jenkins.lolnet.co.nz/job/FactionChat/112/

**Comment by James137137** [comment]
uploaded the same build to http://dev.bukkit.org/bukkit-plugins/factionchat/files/125-faction-chat-v1-10-0-pre-4/

I'm going to assume this issue will be closed soon. Thanks for all your help @tuanjr

**Comment by James137137** [comment]
I'll let the bukkit staff approve the pre-4 version and give it 24 hours. if no1 screams at me then we should be go to go with version 1.10
